name: Code checks

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: lerna bootstrap
      - run: lerna run build
      - run: lerna run test --parallel
